game/urls.py
from django.urls import path
from . import views
app_name = "games"
urlpatterns = [
    path('', views.index, name="games"),
]

game_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('games/', include('game.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name="home"),
    path('about', views.about, name="about"),
    path('contact', views.about, name="contact"),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='login')
]

comments/models.py
from django.db import models

class CommentManager(models.Manager):
    def validate_category(self, postData):
            errors = {}
            if len(postData['title']) < 2:
                errors['title'] = "Title needs to be 2 or more characters."
            if len(postData['body']) < 5:
                errors['body'] = "Comment needs to be 5 or more characters."
            return errors

class Comment(models.Model):
    title = models.CharField(max_length=255, blank=False)
    body = models.TextField(blank=False)

game/models.py
from django.db import models
from users.models import User
from reviews.models import Review

class GameManager(models.Manager):
    pass


class Game(models.Model):
    title = models.CharField(max_length=255, blank=False)
    subtitle = models.CharField(max_length=255, blank=False)
    main_image = models.ImageField(blank=False)
    image_2 = models.ImageField(blank=True)
    image_3 = models.ImageField(blank=True)
    image_4 = models.ImageField(blank=True)
    image_5 = models.ImageField(blank=True)
    image_6 = models.ImageField(blank=True)
    image_7 = models.ImageField(blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    description = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

pages/models.py
from django.db import models

# Create your models here.

reviews/models.py
from django.db import models
from users.models import User
from comments.models import Comment

class ReviewManager(models.Manager):
    def validate_review(self, postData):
        errors = {}
        if len(postData['title']) < 2:
            errors['title'] = "Title needs to be 2 or more characters."
        if len(postData['content']) < 5:
            errors['content'] = "Content needs to be 5 or more characters."
        return errors


class Review(models.Model):
    title = models.CharField(max_length=255, blank=False)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

users/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=255, blank=False)
    username = models.CharField(max_length=255, blank=False)
    email = models.EmailField(blank=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.username

comments/views.py
from django.shortcuts import render

# Create your views here.

game/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'game/index.html', context)

pages/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'pages/home.html', context)

def about(request):
    context = {}
    return render(request, 'pages/about.html', context)

def contact(request):
    context = {}
    return render(request, 'pages/contact.html', context)

reviews/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render

def login(request):
    context = {}
    return render(request, 'users/login.html', context)

def register(request):
    context = {}
    return render(request, 'users/register.html', context)

templates/_partials/_footer.html
{% load static %}
<footer class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
            <img src="{% static 'img/logo.png' %}" class="footer-logo" alt="Game Blog Logo" height="100" width="100">
                <p class="text-white text-center"><i class="fas fa-copyright"></i> 2021, Webkit Development Systems.</p>
                <p class="text-center">
                    <a href="https://facebook.com"><i class="fab fa-facebook"></i></a>
                    <a href="https://google.com"><i class="fab fa-google-plus"></i></a>
                    <a href="https://linkedin.com"><i class="fab fa-linkedin"></i></a>
                    <a href="https://instagram.com"><i class="fab fa-instagram-square"></i></a>
                    <a href="https://github.com"><i class="fab fa-github"></i></a>
                    <a href="https://google.com"><i class="fab fa-google-drive"></i></a>
                </p>
        </div>
        <div class="col-12 col-md-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
                </li>
            </ul>
        </div>
        <div class="col-12 col-md-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
        </div>
    </div>
</footer>

templates/_partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'pages:home' %}">Home</a>
        </li>
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
        </div>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <title>Game Blog - {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include '_partials/_navbar.html' %}
    {% block content %} {% endblock %}
    {% include '_partials/_footer.html' %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

templates/game/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}
{% block content %}
    <div class="jumbotron">
        <img src="{% static 'img/logo.png' %}" class="header-logo" alt="Game Blog Logo" height="250px" width="250px">
        <p class="lead text-center">Where you can find helpful reviews and tips about the latest games.</p>
    </div>
{% endblock %}